name: Android CI

on:
  push:
    branches:
      - master
      - final
  pull_request:
    branches:
      - master
      - final

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Android Lint
        uses: yutailang0119/action-android-lint@v3.1.0
        with:
          report-path: build/reports/*.xml

      - name: Build with Gradle
        run: ./gradlew build

      - name: Godot Android Export
        uses: dulvui/godot-android-export@v2.0.0